# -*- coding: utf-8 -*-
"""AP539

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sux-1PPdYr1RdcLCwfcFHY0v8lm2Y7-E
"""



"""**IMPORTAR DE BIBLIOTECAS**

"""

import pandas as pd
import numpy as np

"""**CARREGAR ARQUIVO**"""

df=pd.read_csv('/content/soybean_bruto.csv')

"""**DETERMINAR OS VALORES FALTANTES E SUBSTITUIR**"""

df=df.replace({"?":np.nan})
for (columnName, columnData) in df.iteritems():
  print('Column Name : ', columnName)
  x=columnData.mode()
  y=columnData.value_counts()
  print(y)
  dadosFaltantes=columnData.isna().mean()*100
  print('Dados faltantes: %.1f'% dadosFaltantes,'%')
  w=str(x[0])
  if (w.replace(".", "", 1).isdigit())==True:
    #se a variável for numérica substitui pela média
    columnData.fillna(columnData.mean(),inplace=True)
  else:
    #se a variável for nominal substitui pela moda
    columnData.fillna(x[0],inplace=True)

  print('')

display(df)